console.log("      My Biodata       ");
console.log("Name: Muhammad Waqas Ahmed");
console.log("Age: 34");
console.log("Gender: Male");
console.log("Qualification: MSc Physics");
console.log("Address: Bhawana, Chiniot Punjab Pakistan");
console.log("Skills: Typescript, JavaScript, HTML, CSS");
console.log("Hobbies: Reading, COding, Travelling.");
console.log("Contact: +923324570707");
console.log("Email: mindworks.agents@gmail.com");
console.log("Thanks your information saved successfully.");